### ISSUE TITLE
Image caption generator

### ISSUE THREAD

**Issue by shubham-jaware** [aswintechguy/Deep-Learning-Projects#4] opened 2024-03-28 17:48 UTC
While training the model,

# train the model
epochs = 20
batch_size = 32
steps = len(train) // batch_size

for i in range(epochs):
    # create data generator
    generator = data_generator(train, mapping, features, tokenizer, max_length, vocab_size, batch_size)
    # fit for one epoch
    model.fit(generator, epochs=1, steps_per_epoch=steps, verbose=1)

Getting error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[28], line 10
      8 generator = data_generator(train, mapping, features, tokenizer, max_length, vocab_size, batch_size)
      9 # fit for one epoch
---> 10 model.fit(generator, epochs=1, steps_per_epoch=1, verbose=1)

File /opt/conda/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:123, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    120     filtered_tb = _process_traceback_frames(e.__traceback__)
    121     # To get the full stack trace, call:
    122     # `keras.config.disable_traceback_filtering()`
--> 123     raise e.with_traceback(filtered_tb) from None
    124 finally:
    125     del filtered_tb

File /opt/conda/lib/python3.10/site-packages/tensorflow/python/data/ops/from_generator_op.py:124, in _from_generator(generator, output_types, output_shapes, args, output_signature, name)
    122   for spec in nest.flatten(output_signature):
    123     if not isinstance(spec, type_spec.TypeSpec):
--> 124       raise TypeError(f"`output_signature` must contain objects that are "
    125                       f"subclass of `tf.TypeSpec` but found {type(spec)} "
    126                       f"which is not.")
    127 else:
    128   if output_types is None:

TypeError: `output_signature` must contain objects that are subclass of `tf.TypeSpec` but found <class 'list'> which is not.

**Comment by aswintechguy** [comment] 2024-04-03 03:21
This is an ongoing issue that is occurring due to the tensorflow version.

We can't run the notebook in kaggle anymore as it's not allowing users to install old tensorflow versions properly. Some of the steps you can try to resolve the issues are below.

1. Use Google Colab / local machine to install tensorflow earlier versions. I installed 2.6.2 at the time of tutorial, if you want to install that specific package. You have to get whl file from here https://pypi.org/project/tensorflow-gpu/2.6.2/#files
2. You can also try earlier version which is <=2.14.0 but after installation, please check the tensorflow version
```
import tensorflow
tensorflow.__version__
```
3. If the tensorflow is installed properly, rest of the notebook will work.

The above steps are temporary solution. I am trying alternate methods to make the script work for newer versions. Will keep posted in this thread.

**Comment by gulshanarya** [comment] 2024-05-22 20:01
Still getting the same kind of error. Could you please update your notebook so that we can resolve the issue? Thanks in advance.

**Comment by aswintechguy** [comment] 2024-05-23 04:09
The issue is already fixed and the notebook & website is also updated. I have checked from my side, and few others also confirmed. Hence closing this thread.

**Closed as completed by aswintechguy** 2024-05-23 04:09 UTC
